### ISSUE TITLE
[QUESTION] - alive?

### ISSUE THREAD

**Issue by erophey7** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#11]
### Question

How alive is the project, and at what stage of development?
I am very interested in this project, and I want to know at what stage the development stalled.

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Stuck on touch and wifi kind of due to no PEP

**Comment by ETCHDEV** [comment]
yes alive

**Comment by n00b69** [comment]
Lisa my beloved

**Comment by n00b69** [comment]
wen port my guide template because this is based off of surya guide and surya guide sucks ass ngl
