### ISSUE TITLE
[BUG] - Phone doesn't boot

### ISSUE THREAD

**Issue by MoonisReal** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#3]
### Description

adding unattended.xml to W:\Windows\Panther does not skip oobe for my device and adding
"cd S:\EFI\Microsoft\Boot\
bcdedit /store BCD /dbgsettings NET BUSPARAMS:1 KEY:1.2.3.4 HOSTIP:169.254.255.255 PORT:50000 NODHCP
bcdedit /store BCD /set {default} debug on"
makes phone completly not booting

### Reproduction steps

```bash
1. copy unattended.xml to W:\Windows\Panther
2. bcdedit /store BCD /dbgsettings NET BUSPARAMS:1 KEY:1.2.3.4 HOSTIP:169.254.255.255 PORT:50000 NODHCP
bcdedit /store BCD /set {default} debug on"
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by ETCHDEV** [comment]
Did you named your XML file as unattended.xml or unattend.xml??

**Comment by ETCHDEV** [comment]
Also which device. And which guide did you follow??

**Comment by MoonisReal** [comment]
1. its was named unattend.xml
2. Xiaomi 11 Lite NE (Lisa)
3.Guide in this repo

**Comment by ETCHDEV** [comment]
Did you copy it before first startup

**Comment by MoonisReal** [comment]
yes i did, before and after first startup, nothing changed.

**Comment by ETCHDEV** [comment]
Does it boot to android??

**Comment by MoonisReal** [comment]
it does boot to android.

**Comment by ETCHDEV** [comment]
Does it stuck on windows loading screen??

**Comment by ETCHDEV** [comment]
After RDP thing

**Comment by MoonisReal** [comment]
it displays boot logo but windows doesn't load after that

**Comment by ETCHDEV** [comment]
I will tell you tomorrow

**Comment by MoonisReal** [comment]
Okay

**Comment by ETCHDEV** [comment]
Did you install windows home or pro on phone

**Comment by ETCHDEV** [comment]
Also, try installing windows again with this command:
dism /apply-image /ImageFile:<path/to/install.wim> /index:2 /ApplyDir:W:\     (index is 2 here).

**Comment by MoonisReal** [comment]
> Did you install windows home or pro on phone

If its based on my main computer then it have pro i think?

**Comment by MoonisReal** [comment]
> Also, try installing windows again with this command: dism /apply-image /ImageFile:<path/to/install.wim> /index:2 /ApplyDir:W:\ (index is 2 here).

Did this and rdp command and file but still nothing.

**Comment by ETCHDEV** [comment]
Ok

**Comment by ETCHDEV** [comment]
It's working for me

**Comment by ETCHDEV** [comment]
I will update the guide

**Comment by MoonisReal** [comment]
Okay

**Comment by MoonisReal** [comment]
is it because i had miui 14 installed?

**Comment by ETCHDEV** [comment]
No, my phone has miui 14

**Comment by ETCHDEV** [comment]
It works though, I will going to try on my friend one too

**Comment by MoonisReal** [comment]
Oh Okay

**Comment by ETCHDEV** [comment]
bcdedit /store BCD /set "{default}" debug on
issue this command

**Comment by ETCHDEV** [comment]
instead of 
bcdedit /store BCD /set {default} debug on

**Comment by ETCHDEV** [comment]
there was " missing

**Comment by ETCHDEV** [comment]
also use windows pro

**Comment by MoonisReal** [comment]
is it pro based on host machine that deploys system?

**Comment by MoonisReal** [comment]
onto phone

**Comment by ETCHDEV** [comment]
onto phone

**Comment by ETCHDEV** [comment]
use index 2

**Comment by ETCHDEV** [comment]
since pro contains rdp not home

**Comment by ETCHDEV** [comment]
also put this command 
bcdedit /store BCD /set "{default}" debug on

**Comment by MoonisReal** [comment]
Okay i will test it and i will let you know

**Comment by MoonisReal** [comment]
it seems no matter its applied as commands it won't boot

**Comment by MoonisReal** [comment]
it does boot without commands and file

**Comment by ETCHDEV** [comment]
Hmm, on my friend s phone, it works

**Comment by MoonisReal** [comment]
maybe its because 11 lite 5G NE?

**Comment by ETCHDEV** [comment]
No, they are same

**Comment by ETCHDEV** [comment]
There is issue with windows installation

**Comment by MoonisReal** [comment]
What build have you used for yours?

**Comment by ETCHDEV** [comment]
Windows pro. Also tried home but home doesn't work

**Comment by MoonisReal** [comment]
i am going to try install latest version but will it work? idk

**Comment by ETCHDEV** [comment]
idk, maybe maybe not
This is not a official windows installation you know

**Comment by MoonisReal** [comment]
i tested with latest build from uup dump and nothing still same

**Comment by ETCHDEV** [comment]
Well, were you going to debug drivers after accessing though RDP since accessing isn't worth it. You can follow uninstallation guide but it will erase data on android side too.

**Comment by MoonisReal** [comment]
Thanks for your assistance and help sir, unfortunally i think its because of my phone.
Have a nice day sir. :)

**Comment by MoonisReal** [comment]
Ok i had to figure it out for a bit now the windows boots but idk if the rdp will work

**Comment by MoonisReal** [comment]
RDP doesn't work so i can't control windows because it says
"RDP disconnected!
1800 The computer cannot establish a connection with another console session on the remote computer because one console session is already in progress."

**Comment by ETCHDEV** [comment]
Restart the phone

**Comment by MoonisReal** [comment]
Okay i will try it

**Comment by MoonisReal** [comment]
Nothing changed i rebooted it twice and nothing
