### ISSUE TITLE
Doesn't work uefi!

### ISSUE THREAD

**Issue by Trexium2** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#4]
### Description

compiled uefi from source, and when I try to start, I write:
recursive exception occurred while dumping the CPU state. Writes 8 more times: 
locate cmd_db_protocol failed:Not found
and at the end: 
UsbPwrCtrlLib_Init Get platform type Error[Not Ready].
Although when running the modified uefi just to install windows, everything is fine, only mass storage does not work (when you start diskpart, it always looks for disks)
![WIN_20230725_18_12_12_Pro](https://github.com/ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE/assets/50524961/3b6681b5-d6bb-48a6-b668-ff4dd5e8f04f)
(sorry for the bad quality, pics from laptop)

### Reproduction steps

```bash
Tell me what to do??
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by ETCHDEV** [comment]
Using the modified uefi is ok for now since no changes are there between latest and old. Also disk part takes time as there are too many partitions.

**Comment by Trexium2** [comment]
okay thank you!
but now another problem
I connected my phone to a PC, through diskpart I write list volume, and there, in addition to PC volumes, there is only one volume with the RAW file system and 286MB in size (you might think that this is a volume from a PC, but no. as soon as I turn off the phone, it disappears)
![Снимок экрана (5)](https://github.com/ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE/assets/50524961/57c1a324-b876-4b4e-a328-6415e6b45446)
(sorry it's in russian)

**Comment by ETCHDEV** [comment]
Run list disk and send a screenshot

**Comment by Trexium2** [comment]
In short, the problem has been solved. entered mass storage mode via msc.sh.

 p.s. through uefi, when I start mass storage, only after 40 minutes the esplisa and winlisa volumes are displayed, but I don’t have time to do anything, after about 5-10 minutes, the phone reboots automatically. 

but anyway, thanks for the help, ETCHDEV. Now I would like to know how to write drivers for the device😅😅

**Comment by ETCHDEV** [comment]
O welcome, btw you can close the issue if problem is sloved
