### ISSUE TITLE
winlisa and esplisa!

### ISSUE THREAD

**Issue by Trexium2** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#5]
### Description

okay thank you!
but now another problem
I connected my phone to a PC, through diskpart I write list volume, and there, in addition to PC volumes, there is only one volume with the RAW file system and 286MB in size (you might think that this is a volume from a PC, but no. as soon as I turn off the phone, it disappears
![Снимок экрана (5)](https://github.com/ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE/assets/50524961/a07e701a-35b8-42b5-8e41-c776c8b952d3)

### Reproduction steps

```bash
?
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by ETCHDEV** [comment]
First type list disk and show me the screenshot
