### ISSUE TITLE
[QUESTION] - ACPI Porting

### ISSUE THREAD

**Issue by MoonisReal** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#7]
### Question

Hi, I would like to help you with ACPI Porting. How i can Help?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by ETCHDEV** [comment]
Well, go to renegade website, see the device status, and the edk2-msm website by renegade

**Comment by ETCHDEV** [comment]
Also, you can ask the people in group on the group in telegram and discord
