### ISSUE TITLE
Removing the ROM completely, replacing it with Windows only

### ISSUE THREAD

**Issue by joeyoropesa-dev** [ETCHDEV/Port-Windows-11-Xiaomi-11-Lite-NE#8]
### Question

Is it possible on any device to replace Android OS with arm64-based Windows so that all partitions in the slots can be earsed that was a part of the android (but not boot.img of course so that we can be sure that we can boot always into fastboot mode and flash the UEFI-based Windows boot.img so that we can actually boot instead to be locked into EDL mode) and after the all partitions except boot partitions are removed, the rest of the biggest space to be used for creating Windows partitions and install Windows-only on it to see will device boots after the missing of the whole Android OS that is now replaced with Windows and renegade project (UEFI-based Windows boot.img)

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by ETCHDEV** [comment]
No, it will not work since partitions are required or it will be bricked to edl. Use can decrease the size of userdata though

**Comment by joeyoropesa-dev** [comment]
> No, it will not work since partitions are required or it will be bricked to edl. Use can decrease the size of userdata though

So... in short there is no way to generate an boot.img that will actually behave like a BIOS to replace Android with Windows due to the hardware security checks? No way to bypass system checks?

**Comment by ETCHDEV** [comment]
nope, only if you have the dev kit of 778g
